### ISSUE TITLE
Expand Tables Width in Terminal Output

### ISSUE THREAD

**Issue by jakeduddy** [pbi-tools/pbi-tools#232]
Tables are squashed to 7 chars per column, if this was doubled it would make a large difference in readibility. Also it would reduce the amount of scrolling required to look at header values.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/74242400/212842376-c16f7e7e-2338-4f25-8184-edc777eb904d.png">

**Comment by mthierba** [comment]
The table width is already (conditionally) set to an explicit width of 80 in order to produce a readable output. However, at least in GitLab, that setting does not seem to be effective. Need to explore a different approach.

Ref: https://github.com/pbi-tools/pbi-tools/blob/b02640e6775c16ce59aced02c88bd16e5c2cb2af/src/PBI-Tools/Deployments/DeploymentManager.Dataset.cs#L481

**Comment by jakeduddy** [comment]
Might be worth trying following? Can't see any other options in the documentation. Might just be gitlabs specific as the logging seems to use ruby on rails which might, not allow a full console feature set
`table.Columns[0].NoWrap();`
or [Expand](https://spectreconsole.net/api/Spectre.Console/Table/4725D2FD)

**Comment by mthierba** [comment]
Resolved in https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.4
