### ISSUE TITLE
Downloading of file https://github.com/pbi-tools/pbi-tools/releases/download/1.0.0-rc.3/pbi-tools.1.0.0-rc.3.zip is blocked

### ISSUE THREAD

**Issue by tarente** [pbi-tools/pbi-tools#264]
Downloading of file https://github.com/pbi-tools/pbi-tools/releases/download/1.0.0-rc.3/pbi-tools.1.0.0-rc.3.zip is blocked due to a potential virus.
![image](https://user-images.githubusercontent.com/110685107/231411054-722f9a5d-e69e-4c04-af89-251c7e31bbae.png)

**Comment by mthierba** [comment]
This is currently expected behaviour since the `pbi-tools.exe` application is not (yet) digitally signed. The _Getting Started_ page describes how to manually unblock the downloaded .zip to circumvent the issue: https://pbi.tools/tutorials/getting-started-cli.html#2-unblock-the-zip-file
Arrangements have already been made to digitally sign future releases of `pbi-tools` - #43 will be updated at that point, Once that is done the file will no longer be falsely classified as a virus on some machines.
