### ISSUE TITLE
Set Credentials SharePoint

### ISSUE THREAD

**Issue by TheBigJones** [pbi-tools/pbi-tools#337]
Hi,
I am currently facing the issue that I don't know how to set the credentials for a table I am loading from SharePoint. I get the following error.
`System.AggregateException: One or more errors occurred. (Failed to save modifications to the server. Error returned: '{"error":{"code":"DMTS_MonikerWithUnboundDataSources","pbi.error":{"code":"DMTS_MonikerWithUnboundDataSources","details":[{"code":"Url","detail":{"type":1,"value":"[https://xyz.sharepoint.com/sites/12345678/"}},{"code":"ConnectionType","detail":{"type":0,"value":"SharePointList"}}],"exceptionCulprit":1}}}](https://xyz.sharepoint.com/sites/12345678/ilename],%22exceptionCulprit%22:1%7D%7D%7D)`

How can I set the credentials? We are working with organizational accounts.

If you need any further infromation, please let me know

**Comment by mthierba** [comment]
# How to set credentials for OAuth2 data sources (ex: SharepointList)

SharePoint, like many other cloud data sources, only support OAuth2 credentials with Power BI. Those credentials cannot be set in a fully automated fashion as they require an interactive login flow.

The way to handle those datasources with `pbi-tools` is to:

* Create them as shared datasources using the Power BI portal,
* Allow the deployment service principal access to the shared datasource, and
* Have `pbi-tools` bind the semantic model to it during model creation.

During deployment, `pbi-tools` allows easy discovery of all external datasources since their details are printed in the deployment logs. Here's an example for a SharePoint List:

![Screenshot 2024-07-11 184326](https://github.com/user-attachments/assets/c3f184a2-ade4-4138-9cad-5135442cdcca)

This example shows how a shared datasource of type `SharePointList` is required, with the url "https://pbitools.sharepoint.com/sites/pbi-tools-demo/".

Navigate to the "Manage Connections and Gateways" portal: https://app.powerbi.com/groups/64f6ae35-a315-4093-bdc3-6e3f4105c21b/gateways. (The url contains a workspace ID - replace those with a valid workspace you have access to in your tenant.)

Access the link via the Settings menu:

![image](https://github.com/user-attachments/assets/3c81f425-e10b-43f1-b47f-89cd1d92c2d0)

Then, create a new "Cloud" datasource with the required type and settings. Choose te "OAuth 2.0" Authentication method and _Edit credentials_ (which triggers an interactive login flow):

![Screenshot 2024-07-11 184724](https://github.com/user-attachments/assets/617db575-4a0d-48ee-b30b-70bcaa485d91)

Once the datasource has been created, go back to its settings and copy the `Connection ID` (a greyed out guid).

Next, select "Manage users". This step is **important**!

![image](https://github.com/user-attachments/assets/a096aec5-39d5-4a4d-a443-0056346f2eb0)

Search for the deployment service principal (which will become the model owner) and share the datasource with a principal as a user:

![Screenshot 2024-07-11 184835](https://github.com/user-attachments/assets/7895ad9c-3655-494d-a1d5-4a8b36929fba)

Lastly, add this snippet to the `pbi-tools` deployment manifest for your semantic model, under options/dataset. Leave the _gatewayId_ as is, but insert your datasource guid under _dataSources_:

```json
          "gateway": {
            "gatewayId": "00000000-0000-0000-0000-000000000000",
            "dataSources": [
              "b8fd6766-dc74-45f6-bcc0-0ef5f67ef068"
            ]
          }
```
![image](https://github.com/user-attachments/assets/1d0c1240-9a12-4a1f-ad14-0930a96bd327)

**IMPORTANT**

`pbi-tools` only performs the datasource binding on newly created datasets (that may be relaxed in a future update). If you already performed a deployment into one of your environments, delete the model and redeploy it, with the new `gateway` setting in place.

Now, all datasources have their required credentials and `pbi-tools` can perform fully automated model deployments and refreshes.

Also note that gateway datasources currently cannot be parameterized, i.e. they cannot be set specifically for each environment. That is a current limitation of `pbi-tools`, which may be lifted in a future update.

**Comment by TheBigJones** [comment]
Hi again,

now I am getting the following error:
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details"....}

                "dataset": {
                    "setCredentials": false,
                    "deployEmbeddedReport": true,
                    "gateway": {
                        "gatewayId": "28698ade-785f-4d17-8157-d8fe84e4c115",
                        "discoverGateways": true
                    },
                    "dataSources": [
                        "e4912901-cd69-4c36-8b16-5af4b2df910c"
                    ]
                }

I also have an SQL connection in my dataset for which I need to set the gateway.

Thank you very much for your fast help :)

**Comment by mthierba** [comment]
> Hi again,
> 
> now I am getting the following error: {"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details"....}
> 
> ```
>             "dataset": {
>                 "setCredentials": false,
>                 "deployEmbeddedReport": true,
>                 "gateway": {
>                     "gatewayId": "28698ade-785f-4d17-8157-d8fe84e4c115",
>                     "discoverGateways": true
>                 },
>                 "dataSources": [
>                     "e4912901-cd69-4c36-8b16-5af4b2df910c"
>                 ]
>             }
> ```
> 
> I also have an SQL connection in my dataset for which I need to set the gateway.
> 
> Thank you very much for your fast help :)

You are using a personal or enterprise gateway with id `28698ade-785f-4d17-8157-d8fe84e4c115`? And your model has one data source that matches the type and address of your gateway data source `e4912901-cd69-4c36-8b16-5af4b2df910c`?

Two things to note here:
* The manifest schema requires the _dataSources_ array to be nested **inside** the `gateway` object - the array won't be recognized anywhere else.
* Gateway binding only takes place on newly created datasets. Did you test this with a dataset that does not yet exist in the target workspace?

**Comment by TheBigJones** [comment]
I have a connection to a SQL Server which is accessible through the gateway with id 28698ade-785f-4d17-8157-d8fe84e4c115. The data source e4912901-cd69-4c36-8b16-5af4b2df910c is the cloud data source I created for my the SharePoint List. What I need to do is having 2 gateway definitions one for the enterprise gateway which I need for the SQL Server and one with gatewayId 00000000-0000-0000-0000-000000000000 for the SharePoint List. Is this possible? When putting the cloud datasource into the enterprise gateway like so

                    "gateway": {
                        "gatewayId": "28698ade-785f-4d17-8157-d8fe84e4c115",
                        "discoverGateways": true,
                        "dataSources": [
                            "e4912901-cd69-4c36-8b16-5af4b2df910c"
                        ]
                    }

I get the following error:
{"error":{"code":"Premium_ASWL_Error","pbi.error":{"code":"Premium_ASWL_Error","parameters":{},"details":[{"code":"Premium_ASWL_Error_Details_Label","detail":{"type":1,"value":"Cloud data source setting is not allowed refresh through gateway."}}],"exceptionCulprit":1}}}

**Comment by mthierba** [comment]
All your data sources have to be accessed through the same gateway - only one gateway can be used for any given model. Since you require the enterprise gateway for your SQL server connection, you'll have to define setup the SharePoint connection on that same gateway.
The approach I shared further up was for the case where **only** cloud data sources were in use, and no explicit gateway is in place.

**Comment by TheBigJones** [comment]
Thanks a lot for your help. What you build is awesome! Keep up the great work 💯 .
