### ISSUE TITLE
Deployment: Can't find workspace

### ISSUE THREAD

**Issue by NPissarra** [pbi-tools/pbi-tools#353]
Hi,

While I'm trying to deploy, I'm getting the message that the workspace can't be found:
![image](https://github.com/user-attachments/assets/41a6133c-f2af-4744-a253-b8a009acaf3a)

The API address does seam it is missing "groups".

I can perfectly call the API with: https://api.powerbi.com/v1.0/myorg/groups/6a0c92a...

This might be the location of this issue:
![image](https://github.com/user-attachments/assets/47831656-bbee-4fca-aaad-ca2dec0487a9)

Regards

**Comment by mthierba** [comment]
Hi,

This is the correct format for the xmla connection string, it is not linked to the API URL format. See here: https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools

Have you checked permissions? Does the service principal you're using have the necessary permissions on the workspace (Contributor or Member)?

Should the xmla connection string for your workspace require some customisation you can also provide a `xmlaDataSource` property inside your environment configuration and provide the full string as specified in your workspace.

Mathias

**Comment by mthierba** [comment]
On further reflection, it appears that the issue is the workspace ID as opposed to the name. The XMLA endpoint requires the name in the connection string. pbi-tools is primarily designed to work with names. It does support providing IDs instead, however, in this particular case an extra name lookup might be required. I'll look into it. Nonetheless, you already have two alternative resolutions (set name or set XMLA connection string in deployment manifest), hence it should not be a blocker.

**Comment by NPissarra** [comment]
I was able to fix it with the name. Also the worspace was not in the proper Premium license. Thanks!

**Comment by mthierba** [comment]
@NPissarra FYI, with the latest 1.2.0 release no workarounds are necessary - workspace Guids in the deployment manifest are now fully supported.
