### ISSUE TITLE
EXTRACT --watch mode

### ISSUE THREAD

**Issue by mthierba** [pbi-tools/pbi-tools#89]
Monitor a .PBIX file open in PBI Desktop, and extract sources whenever the file is saved. Grab the model (if any) from the localhost XMLA port, report sources from the PBIX. This allows very iterative workflows and quick feedback loops.

Two Modes:
- **File path**. Port needs to be supplied, otherwise model will be ignored. Watcher to be stopped explicitly via CTRL+C.
- **Attach to PBID session**. PBIX path and XMLA port is derived from session. Lifetime of watcher is tied to PBID session.

**Comment by BVMather** [comment]
Great idea. I support this, let me know what I can do to help

**Comment by mthierba** [comment]
Brilliant. I've got a working prototype. That was much harder work than expected, but I can already see how useful this will be in the wild. The current version feels pretty stable (I went through numerous implementations...), however will need some beta testers. I'll share this to test during the week.

**Comment by mthierba** [comment]
This is available for testing here: https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-beta.9%2B220221

**Comment by mthierba** [comment]
> Great idea. I support this, let me know what I can do to help

@BVMather Have you had a chance to check out the latest build?

**Comment by benito2313** [comment]
Is it also possible to do a folder watch?
This is focused on a specific file, but i have a folderstructure for different kind of reports.
And i woud like that pbi-tools tracks everything in that folder (no matter how many levels it is in the folder).

Kind regards,

Ben

**Comment by mthierba** [comment]
Hi Ben,
I'd like to understand that scenario better. `pbi-tools` in Watch mode will watch a pbix file _as it is open and being worked on in PBI Desktop_. What should the equivalent be for an entire folder in your view? Are you saying it would help to be less specific and to be able to act on changes on ***any*** file in a folder structure as they happen? 

Mathias

**Comment by benito2313** [comment]
Hi Mathias,

I woud like that pbi tools watches everything in a folder.
This because pbi tools will create separate folders for each PBIX in the same folder as where the pbix is, right?

But then i also mean if you select a folder to watch then the watch function should also look at subfolders.
Like the following:
- Main folder to watch
- - Subfolder 1
- - - PBIX A
- - - PBIX B
- - Subfolder 2
- - - PBIX C
- - - PBIX D
- - Subfolder 3
- - - PBIX E
- - - Subfolder 4
- - - - PBIX F

When you select a repo in devops/github and copy it localy you would also store it like this in a folder structure.

Kind regards,

Ben
