### ISSUE TITLE
pbi-tools deploy: New "Dataset" mode

### ISSUE THREAD

**Issue by mthierba** [pbi-tools/pbi-tools#97]
Support Premium/XMLA/AAS deployments from PbixProj as well as file (*.bim) sources.

# References

## Pre-defined System Variables

- [Azure DevOps](https://docs.microsoft.com/azure/devops/pipelines/build/variables)
- [GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)
- [GitLab](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)

**Comment by 7samat** [comment]
Dataset deployment is superb. This is a gamechanger. These features would really make it complete:
- Conditional refresh
- TE Save to folder compatibility

For the future, I would also like to go towards a model like: Build deployment -> Validate Unit Tests -> Final deployment, as per the article here: https://www.kerski.tech/bringing-dataops-to-power-bi-part5/

Also, I have a question: how to adjust the parameter replacement for Azure DevOps instead of GH?
For example, instead of `%GITHUB_REF_NAME%`,I tried `%variables[‘Build.SourceBranch’]%` and `%Build.SourceBranch%` but it is read as hardcoded text.

**Comment by mthierba** [comment]
Thanks for following up yourself, @7samat - got a busy work schedule at the moment, won't be able to get back to this project till Sunday!
